## Doing K nearest neighbors algorithm

This code will apply the K Nearest Neighbors algorithm (KNN) to the IMDB Dataset based on vectors computed using TF-IDF
We will use a training set of size 20000 for each class (i.e. 20k positive and 20k negative reviews)


In [1]:
import pickle
import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt
from collections import Counter
from nltk.corpus import stopwords
from tqdm import tqdm
from sklearn.decomposition import PCA
import plotly.express as px


## Un comment this lines the first time you run the code
#import nltk
#nltk.download('stopwords')
#nltk.download('punkt')


In [2]:
with open('./normalized_TF_IDF_matrix.pckl', 'rb') as f:
    normalized_TF_IDF_matrix = pickle.load(f)

In [3]:
data = pd.read_csv("./IMDB_Dataset.csv")

In [4]:
data

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [17]:
# Create the training set and test set
positive_Ix = list(data[data['sentiment']=="positive"].index)
negative_Ix = list(data[data['sentiment']=="negative"].index)

train_Ix = np.concatenate([positive_Ix[:20000], negative_Ix[:20000]])
train_labels = np.concatenate([np.repeat(1, 20000), np.repeat(0, 20000)])

In [18]:
train_labels

array([1, 1, 1, ..., 0, 0, 0], shape=(40000,))

In [8]:
normalized_TF_IDF_matrix[positive_Ix, :]

NameError: name 'positive_Ix' is not defined

In [2]:
# The tokenizer of nltk was too slow for that case.
# So, we will use python regular expressions to 
# increase speed

def tokenize_and_count(text):
    """
    This function will tokenize a text using regular
    expressions and counts the number of times each
    token is present in the text
    """
    # Tokenize the text
    p = re.compile("[a-z]+") # Using a regular expression here
    tokens = p.findall(text.lower())
    tokens_counts = Counter(tokens)
    final_dict = {k: v for k, v in sorted(tokens_counts.items(), key=lambda item: item[1], reverse=True)}
    return final_dict

def fair_compose(tokens_positive, tokens_negative, n=100):
    """
    Given the most common words on each class, this function
    will compose a vocabulary with the words that are common
    to both classes while keeping the most popular words for
    each class. 
    """
    vocabulary = []
    i = 0
    j = 0
    while len(set(vocabulary)) < n:
        while True:
            w = list(tokens_positive.keys())[i]
            i +=1
            if w not in stopwords.words('english'):
                vocabulary.append(w)
                break
        while True:
            w = list(tokens_negative.keys())[j]
            j +=1
            if w not in stopwords.words('english'):
                vocabulary.append(w)
                break
    return list(set(vocabulary))

def compute_vocabulary(text_positive, text_negative, n=100):
    """
    This function will create a vocabulary with the n most frequent words
    that are present in the text_positive and text_negative at the same
    time.  
    The function will also remove the stopwords and compute the frequency
    for each word in the positive texts and the negative texts.
    Returns two dictionaries.
    """
    tokens_positive = tokenize_and_count(text_positive)
    del(tokens_positive['br'])
    tokens_negative = tokenize_and_count(text_negative)
    del(tokens_negative['br'])
    vocabulary = fair_compose(tokens_positive, tokens_negative, n)
    return vocabulary

In [3]:
data = pd.read_csv("./IMDB_Dataset.csv")

In [4]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
data.shape

(50000, 2)

In [6]:
# Our training set will be formed by 20k positive and 20k negative reviews
vocabulary_size = 2000
data_positive = data[data['sentiment']=='positive']
data_negative = data[data['sentiment']=='negative']
# Training set
text_positive_train = " ".join(list(data_positive['review'][:20000]))
text_negative_train = " ".join(list(data_negative["review"][:20000]))
# Get the vocabulary
vocabulary = compute_vocabulary(text_positive_train, text_negative_train, vocabulary_size)

In [7]:
len(vocabulary)

2000

In [8]:
def compute_IDF(t, list_of_documents):
    """
    Compute the IDF for a given term t
    Receives a word t and a list of documents.
    Each document on the list has been already
    tokenized.
    """
    denominator = 1
    for d in list_of_documents:
        if t in d:
            denominator +=1
    return np.log(len(list_of_documents)/denominator)

def compute_TF_IDF_vector(document, IDF_dictionary, vocabulary):
    """
    Compute the TF-IDF for a given document.
    The document is already tokenized.
    Returns a list
    """
    n = len(document)
    words = list(set(document)&set(vocabulary))
    terms_counts = Counter(document)
    tf_idf_vector = [0 for i in range(len(vocabulary))]
    for w in words:
        Ix = vocabulary.index(w)
        tf_idf_vector[Ix] = terms_counts[w] / n * IDF_dictionary[w]
    return tf_idf_vector

 



In [9]:
# Tokenize all documents
list_of_documents = []
p = re.compile("[a-z]+") # The regular expression for tokenizing a document
for d in data["review"]:
    list_of_documents.append(p.findall(d.lower()))

In [10]:
# Compute the IDF_dictionary
IDF_dict = {}
for i in tqdm(range(len(vocabulary))):
    t = vocabulary[i]
    IDF_dict[t] = compute_IDF(t, list_of_documents)



100%|██████████| 2000/2000 [01:46<00:00, 18.81it/s]


In [11]:
# Compute the TF-IDF matrix
TF_IDF = []
for i in tqdm(range(len(list_of_documents))):
    d = list_of_documents[i]
    TF_IDF.append(compute_TF_IDF_vector(d, IDF_dict, vocabulary))

100%|██████████| 50000/50000 [00:19<00:00, 2532.80it/s]


In [12]:
TF_IDF_matrix = np.array(TF_IDF)

In [13]:
TF_IDF_matrix.shape

(50000, 2000)

In [14]:
centered_TF_IDF_matrix = TF_IDF_matrix - np.mean(TF_IDF_matrix, axis=1)[:, None]
lines_norms = np.linalg.norm(centered_TF_IDF_matrix, axis=1)
normalized_TF_IDF_matrix = np.zeros_like(centered_TF_IDF_matrix)
for i in range(centered_TF_IDF_matrix.shape[0]):
    normalized_TF_IDF_matrix[i, :] = centered_TF_IDF_matrix[i, :] / lines_norms[i]

In [15]:
normalized_TF_IDF_matrix

array([[-0.0038498 , -0.0038498 , -0.0038498 , ..., -0.0038498 ,
        -0.0038498 , -0.0038498 ],
       [-0.003268  , -0.003268  , -0.003268  , ..., -0.003268  ,
        -0.003268  , -0.003268  ],
       [-0.00354295, -0.00354295, -0.00354295, ..., -0.00354295,
        -0.00354295, -0.00354295],
       ...,
       [-0.003316  , -0.003316  , -0.003316  , ..., -0.003316  ,
        -0.003316  , -0.003316  ],
       [-0.00366195, -0.00366195, -0.00366195, ..., -0.00366195,
        -0.00366195, -0.00366195],
       [-0.00298504, -0.00298504, -0.00298504, ..., -0.00298504,
        -0.00298504, -0.00298504]], shape=(50000, 2000))

In [16]:
np.linalg.norm(normalized_TF_IDF_matrix, axis=1)

array([1., 1., 1., ..., 1., 1., 1.], shape=(50000,))

In [17]:
pca_no_normalized = PCA(n_components=2)
pca_no_normalized.fit(TF_IDF_matrix)
print(pca_no_normalized.explained_variance_ratio_)

[0.00472303 0.00402268]


In [18]:
pca = PCA(n_components=2)
pca.fit(normalized_TF_IDF_matrix)

PCA(n_components=2)

In [19]:
print(pca.explained_variance_ratio_)

[0.00495716 0.00410572]


In [20]:
reduced_data = PCA(n_components=2).fit_transform(TF_IDF_matrix)

In [21]:
np.sum(TF_IDF_matrix.sum(axis=1) == 0)

np.int64(0)

In [22]:
data2plot = pd.DataFrame({'x': reduced_data[:, 0],
                          'y': reduced_data[:, 1], 
                          'sentiment': data["sentiment"]})

In [23]:
data2plot.head()
# only select some values to plot
n = 500
df_positive = data2plot[data2plot['sentiment']=="positive"][:n]
df_negative = data2plot[data2plot['sentiment']=="negative"][:n]
df = pd.concat([df_positive, df_negative])


In [24]:
fig = px.scatter(df, x="x", y="y", color="sentiment", opacity=0.7)
fig.show()

## Let's do a 3D plot

In [25]:
reduced_data3D = PCA(n_components=3).fit_transform(TF_IDF_matrix)

In [26]:
data2plot3D = pd.DataFrame({'x': reduced_data3D[:, 0],
                            'y': reduced_data3D[:, 1], 
                            'z': reduced_data3D[:, 2], 
                            'sentiment': data['sentiment']})
# only select some values to plot
n = 100
df_positive = data2plot3D[data2plot3D['sentiment']=="positive"][:n]
df_negative = data2plot3D[data2plot3D['sentiment']=="negative"][:n]
df = pd.concat([df_positive, df_negative])

In [27]:
fig = px.scatter_3d(df, x='x', y='y', z='z', color='sentiment', opacity=0.9)
fig.show()

In [28]:
import pickle
with open("./normalized_TF_IDF_matrix.pckl", 'wb') as f:
    pickle.dump(normalized_TF_IDF_matrix, f)
